
name = "OrientationObserver"
uuid = "1b08a953-4be3-4667-9a23-4770273e8b7d"
authors = ["s_matsumoto <s_matsumoto@thinkup-sol.co.jp>"]
version = "1.0.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
