
name = "StorageObserver"
uuid = "1b08a953-4be3-4667-9a23-1ecca45f5c89"
authors = ["s_matsumoto <s_matsumoto@thinkup-sol.co.jp>"]
version = "1.0.2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
